import sys
import json
import os
from datetime import datetime


def compute_gc_content(sequence: str) -> float:
    """Compute the GC-content of a DNA sequence as a percentage.

    Case-insensitive. Returns 0.0 for empty sequences.
    """
    sequence = sequence.upper()
    total = len(sequence)
    if total == 0:
        return 0.0
    gc = sequence.count('G') + sequence.count('C')
    return (gc / total) * 100


def parse_fasta(filepath: str) -> list[tuple[str, str]]:
    """Parse a FASTA file and return a list of (header, sequence) tuples.

    Exits with code 1 if the file cannot be read or contains no valid sequences.
    """
    sequences = []
    current_header = None
    current_seq = []

    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                if line.startswith('>'):
                    if current_header is not None:
                        sequences.append((current_header, ''.join(current_seq)))
                    current_header = line[1:].split()[0]
                    current_seq = []
                else:
                    current_seq.append(line)
            if current_header is not None:
                sequences.append((current_header, ''.join(current_seq)))
    except FileNotFoundError:
        print(f"Error: File '{filepath}' not found.", file=sys.stderr)
        sys.exit(1)
    except OSError as e:
        print(f"Error reading file: {e}", file=sys.stderr)
        sys.exit(1)
    except UnicodeDecodeError:
        print(f"Error: File '{filepath}' contains invalid characters and could not be decoded.", file=sys.stderr)
        sys.exit(1)

    if not sequences:
        print("Error: No valid FASTA sequences found in the file.", file=sys.stderr)
        sys.exit(1)

    return sequences


def main() -> None:
    """Entry point: parse arguments, compute GC-content, and print results."""
    if len(sys.argv) < 2:
        print("Usage: python gccompute.py <fasta_file>", file=sys.stderr)
        sys.exit(1)

    filepath = sys.argv[1]
    sequences = parse_fasta(filepath)

    results = []
    txt_lines = []
    timestamp = datetime.now().isoformat()

    for header, seq in sequences:
        gc = compute_gc_content(seq)
        print(header)
        print(gc)
        results.append({"header": header, "gc_content": gc})
        txt_lines.append(f"{header}\n{gc}")

    output_dir = os.path.dirname(os.path.abspath(__file__))

    json_path = os.path.join(output_dir, "results.json")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump({"generated_by": "gccompute.py", "timestamp": timestamp, "sequences": results}, f, indent=2)
    print(f"Results saved to: {json_path}", file=sys.stderr)

    txt_path = os.path.join(output_dir, "results.txt")
    with open(txt_path, "w", encoding="utf-8") as f:
        f.write(f"# Generated by gccompute.py at {timestamp}\n")
        f.write("\n".join(txt_lines) + "\n")
    print(f"Results saved to: {txt_path}", file=sys.stderr)


if __name__ == '__main__':
    main()
